# Oefeningen basis Python

Importeer de volgende bibliotheken: math, numpy en pandas

In [ ]:
import math
import re

import numpy as np
import pandas as pd

## Lijsten en tabellen

Maak een list met volgende waarden: 1, 2, 3, 4, 5 en stop deze in de variabele "id"

In [ ]:
id = [1,2,3,4,5]
print(id)

[1, 2, 3, 4, 5]


Maak een numpy array met volgende waarden: 15, 18, 11, 17, 20 en stop deze in de variabele "leeftijd"

In [ ]:
leeftijd = np.array ([15,18,11,17,20])
print(leeftijd)

[15 18 11 17 20]


Zet de waarden van "leeftijd" om naar een pandas Series en zet het resultaat terug in de variabele "leeftijd".  Verifieer dat het type klopt.

In [ ]:
leeftijd = pd.Series (leeftijd)
print(type(leeftijd))

<class 'pandas.core.series.Series'>


Maak een list met volgende waarden: 54.2, 68.1, 41.7, 59.5, 65.4 en stop deze in de variabele "gewicht"

In [ ]:
gewicht = [54.2, 68.1, 41.7, 59.5, 65.4]
print(gewicht)

[54.2, 68.1, 41.7, 59.5, 65.4]


Maak een numpy array met volgende waarden: 36.5, 37.1, 36.4, 37.2, 36.9 en stop deze in de variabele "temp"

In [ ]:
# hier komt jouw code
import numpy as np
temp = np.array ([36.5, 37.1, 36.4, 37.2, 36.9])
print(temp)

[36.5 37.1 36.4 37.2 36.9]


Zet de array "temp" om naar een list en bewaar het resultaat terug in "temp".  Verifieer dat het type nu wel degelijk een list is.

In [ ]:
temp = list(temp)
print(type(temp))

<class 'list'>


Maak een tabel (data frame) waarin de vorige lijsten de kolommen vormen en stop deze in de variabele "gegevens".  Gebruik voor de namen van de kolommen de namen van de variabelen ("id", "leeftijd", "gewicht" en "temp").

In [ ]:
gegevens = {'Id' : id, 'Leeftijd' : leeftijd, 'Gewicht' : gewicht, 'Temp' : temp}
gegevens = pd.DataFrame(data=gegevens)
print(gegevens)

   Id  Leeftijd  Gewicht  Temp
0   1        15     54.2  36.5
1   2        18     68.1  37.1
2   3        11     41.7  36.4
3   4        17     59.5  37.2
4   5        20     65.4  36.9


Toon de kolomnamen van de tabel

In [ ]:
columnName = list(gegevens.columns.values)
print(columnName)

['Id', 'Leeftijd', 'Gewicht', 'Temp']


Toon het aantal kolommen

In [ ]:
print(gegevens.keys().size)

4


Toon de kolom met naam 'temp'

In [ ]:
print(gegevens.Temp)

0    36.5
1    37.1
2    36.4
3    37.2
4    36.9
Name: Temp, dtype: float64


Toon de 2e kolom uit de tabel zonder de naam te gebruiken

In [ ]:
print(gegevens.iloc[:,1])

0    15
1    18
2    11
3    17
4    20
Name: Leeftijd, dtype: int32


Verwijder de derde rij uit de tabel

In [ ]:
# del gegevens['Gewicht']
# print(gegevens)

Toon de 3e rij uit de tabel

In [ ]:
print(gegevens.iloc[2])

Id           3.0
Leeftijd    11.0
Gewicht     41.7
Temp        36.4
Name: 2, dtype: float64


Toon de 2e en de 4e rij uit de tabel

In [ ]:
print(gegevens.iloc[[1,3]])

   Id  Leeftijd  Gewicht  Temp
1   2        18     68.1  37.1
3   4        17     59.5  37.2


Toon de 2e tot en met 4e rij uit de tabel

In [ ]:
print(gegevens.iloc[1:4])

   Id  Leeftijd  Gewicht  Temp
1   2        18     68.1  37.1
2   3        11     41.7  36.4
3   4        17     59.5  37.2


Bereken de minimum en maximum leeftijd.  Je kan dit doen door de methoden "min()" en "max()" op te roepen op de kolom.

In [ ]:
print(gegevens.iloc[:,1].min()) # of print(gegevens['Leeftijd'].min())
print(gegevens.iloc[:,1].max()) # of print(gegevens['Leeftijd'].max())

11
20


Bereken de som van alle gewichten en deel die door het aantal gewichten (bereken dus het gemiddelde gewicht).  Je kan hiervoor de methode "sum()" oproepen op de kolom.  De lengte van de kolom vind je met de functie "len()".
Bemerk dat sum() een methode is die je op een object oproept (de kolom) en len() een functie is die niet aan een object gekoppeld is (vergelijkbaar met een static method in java).  Dit laat zien dat Python een hybride taal is waarin je tegelijk OO en procedureel kan programmeren.
Toon het resultaat met 3 cijfers na de komma.  Hier zie je een hint hoe je dat kan doen:
```python
print("pi is{:10.2f}".format(math.pi))
```

In [ ]:
print(round(gegevens.iloc[:,2].sum()/len(gegevens.iloc[:,2]),3))

57.78


Bereken alle gewichten in gram (vermenigvuldig ze dus met 1000) maar verander de tabel niet.  Geef het resultaat weer als een Python list.
Zie je wat er met de laatste waarde gebeurt?  Hoe komt dit?

In [ ]:
newLijst = [gegevens.iloc[:,2]*1000]
print(newLijst)

[0    54200.0
1    68100.0
2    41700.0
3    59500.0
4    65400.0
Name: Gewicht, dtype: float64]


Zet alle temperaturen om naar Fahrenheit, rondt deze af op 1 cijfer na de komma en zet deze waarden in de tabel in een nieuwe kolom met de naam "temp_far".
Hint: een kolom uit een data frame is een Series en heeft een methode "round()"

In [ ]:
# een lege kolom 'C' toevoegen aan de DataFrame
# gegevens['temp_far'] = None

gegevens['temp_far'] = round((gegevens.iloc[:,3]*9/5)+32,1)

Bewaar de tabel in een bestand "gegevens.csv".  Gebruik je lokale settings voor de seperator en het formatteren van kommagetallen.

In [ ]:
gegevens.to_csv("gegevens.csv", sep=";", decimal=",", index=False)

Open de tabel in excel of open office. Als je het bestand juist bewaard hebt, zou dit moeten lukken.  Je kan het bestand eventueel ook uploaden naar google drive en openen met google spreadheets.
Voeg er een kolom aan toe met de naam "extra".  Zet volgende gegevens in de kolom: "hallo", "dit", "is", "een", "testje"
Bewaar het bestand als csv.

Lees de aangepaste tabel nu terug in en kijk na of de nieuwe kolom goed werd ingelezen.

In [ ]:
gegevens = pd.read_csv("test.csv", sep=";", decimal=",")
print(gegevens)

   Id  Leeftijd  Gewicht  Temp  Temp_far   Extra
0   1        15     54.2  36.5      97.7   hallo
1   2        18     68.1  37.1      98.8     dit
2   3        11     41.7  36.4      97.5      is
3   4        17     59.5  37.2      99.0     een
4   5        20     65.4  36.9      98.4  testje


Verwijder de kolom “id”.

In [ ]:
del gegevens['Id']
print(gegevens)

   Leeftijd  Gewicht  Temp  Temp_far   Extra
0        15     54.2  36.5      97.7   hallo
1        18     68.1  37.1      98.8     dit
2        11     41.7  36.4      97.5      is
3        17     59.5  37.2      99.0     een
4        20     65.4  36.9      98.4  testje


Voeg een rij toe met [ 30, 74.1, 36.5, 97.7 ] als waarden (zoek eens op hoe je dat kan doen):

In [ ]:
# loc is alleen voor en rij toe te voegen
# nieuwe_rij = [30, 74.1, 36.5, 97.7, '']
# gegevens.loc[len(gegevens)] = nieuwe_rij
# print(gegevens)

Voeg een kolom “lengte” toe met gegevens: 160, 175, 162, 169, 179

In [ ]:
lengteData = [160, 175, 162, 169, 179]
gegevens['Lengte'] = lengteData
print(gegevens)

   Leeftijd  Gewicht  Temp  Temp_far   Extra  Lengte
0        15     54.2  36.5      97.7   hallo     160
1        18     68.1  37.1      98.8     dit     175
2        11     41.7  36.4      97.5      is     162
3        17     59.5  37.2      99.0     een     169
4        20     65.4  36.9      98.4  testje     179


Bereken de BMI van iedere persoon in de tabel en rond deze af op 1 cijfer na de komma.
De BMI is gelijk aan het gewicht gedeeld door de lengte in het kwadraat.  De lengte moet in meter uitgedrukt zijn en het gewicht in kilogram.
Het resultaat moet een list zijn.

In [ ]:
# for gewicht, lengte in zip(df['Gewicht'], df['Lengte'])] is a loop that iterates through each pair of corresponding weight and height values from the Gewicht and Lengte columns of a DataFrame df. The zip() function is used to create an iterator that aggregates the elements from each of the iterables passed to it as arguments. In this case, it aggregates the values from the Gewicht and Lengte columns of the DataFrame. The loop then assigns the current weight and height values to the variables gewicht and lengte, respectively, in each iteration of the loop. This allows us to calculate the BMI for each individual based on their weight and height.

BMI = [round(gewicht / ((lengte / 100) ** 2), 1) for gewicht, lengte in zip(gegevens['Gewicht'], gegevens['Lengte'])];

Voeg deze BMI als kolom toe aan de tabel.

In [ ]:
# Aanmaken van een nieuwe Kolom met de lijst als enige kolom
gegevens['BMI'] = BMI
print(gegevens)

   Leeftijd  Gewicht  Temp  Temp_far   Extra  Lengte   BMI
0        15     54.2  36.5      97.7   hallo     160  21.2
1        18     68.1  37.1      98.8     dit     175  22.2
2        11     41.7  36.4      97.5      is     162  15.9
3        17     59.5  37.2      99.0     een     169  20.8
4        20     65.4  36.9      98.4  testje     179  20.4


Toon alle gewichten die kleiner of gelijk zijn aan 60 uit de kolom gewicht als een list.

In [ ]:
Gewicht2 = []

for element in gegevens.Gewicht:
    if element <= 60:
        Gewicht2.append(element)


print(Gewicht2)


[54.2, 41.7, 59.5]


Vervang in de kolom leeftijd alle leeftijden groter of gelijk aan 18 door 19.
Krijg je een warning?  Je kan dit oplossen door gegevens.loc[] te gebruiken.

In [ ]:
# Vervang leeftijden groter of gelijk aan 18 door 19
gegevens.loc[gegevens['Leeftijd'] >= 18, 'Leeftijd'] = 19

# Print de aangepaste DataFrame
print(gegevens)

   Leeftijd  Gewicht  Temp  Temp_far   Extra  Lengte   BMI
0        15     54.2  36.5      97.7   hallo     160  21.2
1        19     68.1  37.1      98.8     dit     175  22.2
2        11     41.7  36.4      97.5      is     162  15.9
3        17     59.5  37.2      99.0     een     169  20.8
4        19     65.4  36.9      98.4  testje     179  20.4


Vind alle temperaturen van de personen die ouder zijn dan 16 jaar.  Geef het resultaat weer als een numpy array.

In [ ]:
TempData = np.array(gegevens.loc[gegevens['Leeftijd'] > 16, 'Temp'])


print(TempData)
print(type(TempData))

[37.1 37.2 36.9]
<class 'numpy.ndarray'>


## Sport data

Bepaal de separator en teken voor kommagetallen in het bestand "sportData.csv".
Lees het bestand "sportData.csv" vervolgens in en zet het resultaat in de variabele "sport".
Toon tenslotte alle kolommen van de tabel, samen met hun type.

In [ ]:
sport = pd.read_csv('sportdata.csv', delimiter=';')

display(sport) # Met print kan ook

display(sport.dtypes) # Met print kan ook

leeftijd geslacht      sport  keer per week  uren per week
0         12        m       geen              0              0
1         12        m  basketbal              1              2
2         13        m    voetbal              2              4
3         11        v    voetbal              2              4
4         13        v       geen              0              0
..       ...      ...        ...            ...            ...
70        12        v     turnen              2              4
71        11        v       judo              2              4
72        11        v    voetbal              1              2
73        12        v       geen              0              0
74        11        v     anders              1              2

[75 rows x 5 columns]

leeftijd          int64
geslacht         object
sport            object
keer per week     int64
uren per week     int64
dtype: object

Hoeveel data-rijen zijn er in dit bestand?

In [ ]:
print("Het aantal rijen in het sportdata.csv bestand:", len(sport) )

Het aantal rijen in het sportdata.csv bestand: 75


Bepaal alle mogelijke waarden die in de kolom "sport" voorkomen.

In [ ]:
waarde = sport['sport'].unique()
print(waarde)

['geen' 'basketbal' 'voetbal' 'klimmen' 'turnen' 'anders' 'zwemmen' 'judo'
 'fitness']


De kolom "sport" bevat blijkbaar de waarden "Niet bekend" en "niet geweten".  Deze waarden zijn geen geldige waarde en zouden we willen lezen als een ontbrekende waarde.
In Python worden verschillende waarden gebruikt om aan te duiden dat er een waarde ontbreekt.  De meest voorkomende is NaN.
Lees het bestand terug in, maar gebruikt de optie om aan te geven welke strings als ontbrekende waarde moeten worden herkend.
Controleer of het gelukt is door alle mogelijke waarden van de kolom "sport" te bekijken.  De twee ongeldige waarden zouden nu weg moeten zijn en vervangen door de waarde nan.

In [ ]:
sport2 = pd.read_csv('sportdata.csv', delimiter=';', na_values=['geen'])
display(sport2)

leeftijd geslacht      sport  keer per week  uren per week
0         12        m        NaN              0              0
1         12        m  basketbal              1              2
2         13        m    voetbal              2              4
3         11        v    voetbal              2              4
4         13        v        NaN              0              0
..       ...      ...        ...            ...            ...
70        12        v     turnen              2              4
71        11        v       judo              2              4
72        11        v    voetbal              1              2
73        12        v        NaN              0              0
74        11        v     anders              1              2

[75 rows x 5 columns]

Geef een commando dat voor iedere kolom bepaalt of er ontbrekende waarden in voor komen.

In [ ]:
print(sport2.isna().any())

leeftijd         False
geslacht         False
sport             True
keer per week    False
uren per week    False
dtype: bool


Welke rijen bevatten ontbrekende (NaN) waarden?  Geef een list met alle rijnummers waarin minstens 1 ontbrekende waarde zit.

In [ ]:
# Spory
# Create a list of row numbers with missing values
missing_rows = sport2.isna().any(axis=1).index[sport2.isna().any(axis=1)].tolist()

print("Rijnummers met ontbrekende waarden: ", missing_rows)

Rijnummers met ontbrekende waarden:  [0, 4, 9, 10, 15, 17, 18, 19, 24, 27, 30, 33, 36, 39, 43, 58, 64, 73]


Verwijder alle rijen met ontbrekende waarden en stop het resultaat in een nieuwe tabel "sport_new".  De oorspronkelijke tabel mag niet veranderd worden.

In [ ]:
sport_new = sport2.dropna()
print(sport_new)

    leeftijd geslacht      sport  keer per week  uren per week
1         12        m  basketbal              1              2
2         13        m    voetbal              2              4
3         11        v    voetbal              2              4
5         12        v    klimmen              1              2
6         12        m     turnen              1              2
7         11        m    voetbal              1              2
8         12        v     anders              1              2
11        11        m     turnen              2              4
12        12        v     anders              2              4
13        12        m    voetbal              1              2
14        13        v    zwemmen              2              4
16        11        m    klimmen              2              4
20        13        m  basketbal              2              4
21        11        v    voetbal              2              4
22        12        m     turnen              1        

Wat is het maximum van kolom "leeftijd"?

In [ ]:
print(sport2['leeftijd'].max())

14


Wat is de som van alle waarden van kolom "keer per week" die groter zijn dan 1?

In [ ]:
# Select only the rows where "keer per week" is greater than 1
selected_rows = sport_new.loc[sport_new['keer per week'] > 1]
# Calculate the sum of the "keer per week" column in the selected rows
totaal = selected_rows['keer per week'].sum()

print(totaal)

97


Geef een lijst van alle sporten die beoefend worden door mensen die meer dan 3 keer per week sporten.  Geef het resultaat als een Series.

In [ ]:
rij = pd.Series(sport_new.loc[sport_new['keer per week'] > 3, 'sport'])
rij = rij.drop_duplicates()

print(rij)

29      voetbal
31      klimmen
37    basketbal
59         judo
Name: sport, dtype: object


## Programmeren

Hier staan een aantal programmeeropdrachten om gewoon te raken aan de syntax en mogelijkheden van Python.

### Dobbelsteen
Schrijf een programma dat 6000 keer met de dobbelsteen rolt en telt hoeveel keer iedere waarde voorkomt.  Probeer geen lussen te moeten schrijven.  Je kan dit doen door te starten met een numpy array van 6000 willekeurige getallen tussen 1 en 6.

Voorbeeld van de werking (dit kan afwijken omdat het willekeurige getallen zijn, maar alle getallen zouden rond de 1000 moeten liggen):

```{text}
Aantal enen: 1007
Aantal tweeën: 994
Aantal drieën: 1006
Aantal vieren: 995
Aantal vijven: 998
Aantal zessen: 1000
```

In [ ]:
random = np.random.randint(1, 7,size=6000)
enen = 0
tweeen = 0
drieen = 0
vieren = 0
vijven = 0
zessen = 0

for i in random:
    if i == 1:
        enen = enen + 1
    if i == 2:
        tweeen = tweeen + 1
    if i == 3:
        drieen = drieen + 1
    if i == 4:
        vieren = vieren + 1
    if i == 5:
        vijven = vijven + 1
    if i == 6:
        zessen = zessen + 1
print("""
Aantal enen {0:0d}
Aantal tweeën {1:0d}
Aantal drieën {2:0d}
Aantal vieren {3:0d}
Aantal vijven {4:0d}
Aantal zessen {5:0d}
""".format(enen,tweeen,drieen,vieren,vijven,zessen))

# Dit kan ook
# random = np.random.randint(1, 7, size=6000)
# counts = np.bincount(random)
#
# print("Aantal enen:", counts[1])
# print("Aantal tweeën:", counts[2])
# print("Aantal drieën:", counts[3])
# print("Aantal vieren:", counts[4])
# print("Aantal vijven:", counts[5])
# print("Aantal zessen:", counts[6])


Aantal enen 976
Aantal tweeën 1029
Aantal drieën 1060
Aantal vieren 973
Aantal vijven 985
Aantal zessen 977



### Kerstboom

Schrijf een programma om een kerstboom af te drukken met behulp van ‘*’ tekens. De breedte van de boom wordt als een oneven geheel getal (13..29)  ingegeven. Indien niet voldaan is aan deze voorwaarde wordt de breedte op 13 ingesteld.

Eerst moet je het midden van de boom bepalen aan de hand van de breedte.
Vervolgens druk je de boom regel per regel af.
Opmerking: de stam bestaat altijd uit 4 regels met een breedte van 3.
Gebruik een for-lus om de boom af te drukken.

Je kan het getal inlezen met volgende code:
```{python}
breedte = int(input("Geef de breedte de van kerstboom (oneven getal in bereik 13..29):"))
```
Als je iets wil printen zonder newline op het einde (zoals System.out.print() in Java), dan kan dat als volgt:
```{python}
print("hello, ", end='')
print("world!")
```
Je kan een aantal keer hetzelfde karakter in een string zetten met:
```{python}
karakter = "*"
aantal = 5
print(karakter * aantal)
```

Voorbeeld van de werking:

```{text}
Geef de breedte de van kerstboom (oneven getal in bereik 13..29): 13

      *
     ***
    *****
   *******
  *********
 ***********
*************
     ***
     ***
     ***
     ***
```

In [44]:
# Input user (breedte)
breedte = int(input("Geef de breedte de van kerstboom (oneven getal in bereik 13..29):"))

# Controleren of dat de breedte tussen 13 en 29 valt (inclusief). Indien niet wordt breedte op 13 gezet.
if not (13 <= breedte <= 29):
    breedte = 13

# Bepaal het midden van de boom
midden = breedte // 2

# Boom maken
for i in range(midden):
    print(" " * (midden - i) + "*" * (2 * i + 1))

# Stam maken
for i in range(4):
    print(" " * (midden - 1) + "***")

      *
     ***
    *****
   *******
  *********
 ***********
     ***
     ***
     ***
     ***


### Geheim schrift
Schrijf een programma om berichten te coderen en te decoderen zoals Julius Caesar deed.
Het programma vraagt eerst een bericht.  Dit bericht wordt naar hoofdletters omgezet.
Daarna vraagt het programma aan de gebruiker of het bericht gecodeerd of gedecodeerd moet worden.
Om te coderen, doorloopt het programma alle letters in het bericht en verschuift deze letter telkens een aantal plaatsen (zet deze verschuiving in een variabele).
Met een verschuiving van 3 wordt bijvoorbeeld de letter 'A' een 'D'.  Indien je aan het einde van het alfabet komt begin je terug bij de 'A' (een 'Z' wordt in dit geval een 'C'). Bij het decoderen doe je uiteraard het tegenovergestelde.  Je kan dit heel snel doen door gebruik te maken van de ASCII code van ieder karakter (je mag ervan uitgaan dat alle karakters in de ASCII set passen).
Als een karakter geen letter is, dan wordt die gewoon ongecodeerd (of ongedecodeerd) weergegeven.

Voorbeeld van werking (de verschuiving staat hier op 6):
```{text}
Geef een bericht: The quick brown fox jumps over the lazy dog.
Wil je dit encoderen? J
Gecodeerd bericht:
ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.

Geef een bericht: ZNK WAOIQ HXUCT LUD PASVY UBKX ZNK RGFE JUM.
Wil je dit encoderen? N
Gedecodeerd bericht:
THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG.
```
Hint: je kan de code heel compact maken als je gebruik maakt van de modulo (%) operator.
Hint: je kan een karakter omzetten naar zijn ASCII code met "ord(c)" en omgekeerd kan je een ASCII code naar een karakter omzetten met "chr(code)"

In [43]:
# Input user (bericht)
bericht = str(input("Geef een bericht: "))

# Naar hoofdletters
bericht = bericht.upper()

# Yes or no
encdec = str(input("Wil je dit encoderen? (Y/N): "))

# new_bericht initialiseren
new_bericht = ""
# Dit stukje code codeert of decodeert het bovenstaande bericht.
if encdec == "Y" or encdec == "y":
    for i in bericht:
        temp = ord(i)+1
        new_bericht = new_bericht + chr(temp)
    print("Gecodeerd bericht:\n" + new_bericht)
elif encdec == "N" or encdec == "n":
    for i in bericht:
        temp = ord(i)-1
        new_bericht = new_bericht + chr(temp)
    print("Gedecodeerd bericht:\n" + new_bericht)
else: print("Ongeldige invoer voor encoderen/decoderen. Voer 'Y' of 'N' in.")

Gecodeerd bericht:
FMJBT


### Vervangen
Maak een functie "vervang(lijst, te_zoeken, vervanging)" die in een list op zoek gaat naar een waarde en die vervangt door een andere.

In [46]:
def vervang (lijst, te_zoeken, vervanging):
    """
    Vervangt een waarde in de lijst door een andere waarde.

    Parameters:
        lijst (list): De lijst waarin gezocht wordt.
        te_zoeken: De waarde die gezocht wordt.
        vervanging: De waarde waarmee te_zoeken vervangen wordt.

    Returns:
        list: De bijgewerkte lijst.
    """
    for i in range(len(lijst)):
        if lijst[i] == te_zoeken:
            lijst[i] = vervanging
    return lijst

Test de functie uit door in de list [ 10, 20, 30, 30, 40, 30, 0 ] de waarde 30 te vervangen door 42.
Probeer of je functie ook werkt op een numpy array en een pandas Series.  Dat zou moeten lukken.

In [54]:
# import
import numpy as np
import pandas as pd

# De normale lijst
testN = [ 10, 20, 30, 30, 40, 30, 0 ]
testN_new = vervang(testN, 30, 42)
print(testN_new) # New

# Numpy array
tempNp = np.array([ 10, 20, 30, 30, 40, 30, 0 ])
testNp_new = vervang(tempNp, 30, 42)
print(testNp_new) # New

# Pandas Series
tempNd = pd.Series([ 10, 20, 30, 30, 40, 30, 0 ])
tempNd_new = vervang(tempNd, 30, 42)
print(tempNd_new) # New

[10, 20, 42, 42, 40, 42, 0]
[10 20 42 42 40 42  0]
0    10
1    20
2    42
3    42
4    40
5    42
6     0
dtype: int64


### Wachtwoorden
Een goed wachtwoord kiezen, is voor sommige gebruikers een ware opgave.  We willen een programma maken waarin de gebruiker een nieuw wachtwoord moet kiezen.  Dit moet (omdat we het graag ingewikkeld maken) minstens 8 karakters lang zijn, minstens 1 hoofdletter, 1 kleine letter, een cijfer en een leesteken bevatten.
Maak een functie "is_goed_wachtwoord" die een wachtwoord als parameter meekrijgt en een boolean teruggeeft.  Die boolean is true als het gegeven wachtwoord voldoet aan alle eisen.  De functie geeft ook een foutmelding op het scherm als het wachtwoord niet goed is.
Maak dan een programma dat een nieuw wachtwoord vraagt totdat alle eisen voldaan zijn.

Voorbeeld van de werking:

```{text}
Geef een nieuw wachtwoord: ww
Het moet minstens 8 karakters lang zijn
Geef een nieuw wachtwoord: wachtwoord
Het moet minstens 1 hoofdletter bevatten
Geef een nieuw wachtwoord: WACHTWOORD
Het moet minstens 1 kleine letter bevatten
Geef een nieuw wachtwoord: Wachtwoord
Het moet minstens 1 cijfer bevatten
Geef een nieuw wachtwoord: Wachtw00rd
Het moet minstens 1 leesteken bevatten
Geef een nieuw wachtwoord: Wachtw00rd!
Je nieuwe wachtwoord is goedgekeurd!
```

Hint: je kan heel eenvoudig itereren door de karakters van een string met:
```{python}
for c in string:
    ...
```

In [70]:
import re
def is_goed_wachtwoord (wachtwoord):
    # Minstens 8 Karakters
    if not len(wachtwoord) >= 8:
        print("Het wachtwoord moet minstens 8 karakters lang zijn.")
        return False
    # Minstens 1 Hoofdletter
    if not re.search("[A-Z]", wachtwoord):
        print("Het wachtwoord moet minstens 1 hoofdletter bevatten.")
        return False
    # Minstens 1 Kleine letter
    if not re.search("[a-z]", wachtwoord):
        print("Het wachtwoord moet minstens 1 kleine letter bevatten.")
        return False
    # Minstens 1 Cijfer
    if not re.search("[0-9]", wachtwoord):
        print("Het wachtwoord moet minstens 1 cijfer bevatten.")
        return False
    # Minstens 1 Leesteken
    if not re.search("[^a-zA-Z0-9]", wachtwoord):
        print("Het wachtwoord moet minstens 1 leesteken bevatten.")
        return False
    # Else
    return True


# Input user (wachtwoord)
wachtwoord = str(input("Geef een nieuw wachtwoord: "))

while not is_goed_wachtwoord(wachtwoord):
    # Input user (wachtwoord)
    wachtwoord = str(input("Geef een nieuw wachtwoord: "))
    if is_goed_wachtwoord(wachtwoord):
        print("Je nieuwe wachtwoord is goedgekeurd!")
        break

Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 1 hoofdletter bevatten.
Het wachtwoord moet minstens 1 hoofdletter bevatten.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtwoord moet minstens 8 karakters lang zijn.
Het wachtw